import { getLLMProvider } from "@/lib/ai/client";
import { buildIssueEditorPrompt } from "@/lib/ai/prompts/issue-editor";
import { issueDraftSchema } from "@/lib/ai/schema";
import type {
  CurationInput,
  GenerateIssueOptions,
  IssueDraft,
  LLMProvider,
} from "@/lib/ai/types";

type CurateNewIssueOptions = Partial<GenerateIssueOptions> & {
  provider?: LLMProvider;
  retryCount?: number;
};

const DEFAULT_MAX_OUTPUT_TOKENS = 1024;
const DEFAULT_RETRY_COUNT = 1;

function toErrorMessage(error: unknown): string {
  if (error instanceof Error) return error.message;
  return String(error);
}

function buildFallbackIssueDraft(input: CurationInput): IssueDraft {
  const maxSections = Math.max(1, input.maxSections ?? 3);
  const trendSignals =
    input.trendSignals.length > 0 ? input.trendSignals : ["에디터 추천"];

  const sections: IssueDraft["sections"] = Array.from(
    { length: maxSections },
    (_, index) => {
      const signal = trendSignals[index % trendSignals.length];
      return {
        id: `fallback-theme-${index + 1}`,
        eyebrow: `FALLBACK EDIT ${index + 1}`,
        title: `${signal} curation`,
        subtitle: "Fallback section generated by curator",
        source: { type: "theme", query: signal, size: 6 },
        size: 6,
      };
    }
  );

  return {
    vol: input.issueMeta.vol,
    season: input.issueMeta.season,
    title: `Fallback issue for ${input.issueMeta.city}`,
    titleHighlight: "fallback",
    dek: "모델 출력 검증에 실패해 fallback 초안을 사용합니다.",
    date: input.issueMeta.date,
    city: input.issueMeta.city,
    coverLabel: "FALLBACK COVER",
    coverImage:
      "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&q=85&w=1800",
    coverAlt: "Fallback editorial cover image",
    coverFocal: "center 35%",
    primaryCtaLabel: "COLLECTION 보기",
    primaryCtaHref: "/feed",
    secondaryCtaLabel: "LOOKBOOK",
    secondaryCtaHref: "/saved?tab=looks",
    tickerItems: [
      `VOL ${input.issueMeta.vol}`,
      input.issueMeta.season,
      input.issueMeta.city,
    ],
    sections,
  };
}

export async function curateNewIssue(
  input: CurationInput,
  options: CurateNewIssueOptions = {}
): Promise<IssueDraft> {
  const provider = options.provider ?? getLLMProvider();
  const retryCount = Math.max(0, options.retryCount ?? DEFAULT_RETRY_COUNT);
  const providerOptions: GenerateIssueOptions = {
    maxOutputTokens: options.maxOutputTokens ?? DEFAULT_MAX_OUTPUT_TOKENS,
    temperature: options.temperature,
  };

  // 프롬프트는 별도 모듈에서 구성한다. (Gemini provider 단계에서 직접 전달 예정)
  const promptMessages = buildIssueEditorPrompt(input);
  void promptMessages;

  let lastError: unknown = null;

  for (let attempt = 0; attempt <= retryCount; attempt += 1) {
    try {
      const draft = await provider.generateIssueDraft(input, providerOptions);
      return issueDraftSchema.parse(draft);
    } catch (error) {
      lastError = error;
    }
  }

  try {
    const fallback = buildFallbackIssueDraft(input);
    return issueDraftSchema.parse(fallback);
  } catch (fallbackError) {
    throw new Error(
      `Failed to curate issue draft. provider=${provider.name}; lastError=${toErrorMessage(lastError)}; fallbackError=${toErrorMessage(fallbackError)}`
    );
  }
}
